In [24]:
documents = ['The sky is blue', 'The sun is bright', 'The sun in the sky is bright', 'we can see the shining sun, the bright sun']

In [25]:
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer

tf_idf_vect = TfidfVectorizer(stop_words='english')
new_doc = tf_idf_vect.fit_transform(documents)
print(new_doc.toarray())
print(tf_idf_vect.get_feature_names())
scores = np.sum(new_doc, axis=0)
scores = np.ravel(scores)
print(scores)

[[0.78528828 0.         0.         0.6191303  0.        ]
 [0.         0.70710678 0.         0.         0.70710678]
 [0.         0.53256952 0.         0.65782931 0.53256952]
 [0.         0.36626037 0.57381765 0.         0.73252075]]
['blue', 'bright', 'shining', 'sky', 'sun']
[0.78528828 1.60593668 0.57381765 1.27695961 1.97219705]


In [26]:
results = list()
for i in range(len(tf_idf_vect.get_feature_names())):
    results.append((tf_idf_vect.get_feature_names()[i], scores[i]))
results.sort(key = lambda results: results[1], reverse=True)
results

[('sun', 1.9721970507561841),
 ('bright', 1.605936677684143),
 ('sky', 1.27695960978985),
 ('blue', 0.7852882757103967),
 ('shining', 0.5738176501168697)]

In [27]:
def get_scores(documents):
    tf_idf_vect = TfidfVectorizer(stop_words='english')
    new_doc = tf_idf_vect.fit_transform(documents)
    scores = np.sum(new_doc, axis=0)
    scores = np.ravel(scores)
    
    results = list()
    for i in range(len(tf_idf_vect.get_feature_names())):
        results.append((tf_idf_vect.get_feature_names()[i], scores[i]))
    results.sort(key = lambda results: results[1], reverse=True)
    return results

print(get_scores(documents))

[('sun', 1.9721970507561841), ('bright', 1.605936677684143), ('sky', 1.27695960978985), ('blue', 0.7852882757103967), ('shining', 0.5738176501168697)]


In [36]:
x = {0:1, 1:0, 2:5, 3:4, 4:3}
print(x)
{k: v for k, v in sorted(x.items(), key=lambda item: item[1])}

{0: 1, 1: 0, 2: 5, 3: 4, 4: 3}


{1: 0, 0: 1, 4: 3, 3: 4, 2: 5}